spring:
  application:
    name: TweakPay

  datasource:
    url: jdbc:mysql://${db.host}:${db.port}/${db.name}?serverTimezone=UTC&allowPublicKeyRetrieval=true&useSSL=false
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:secret}

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092,localhost:9094,localhost:9096}
    #Producer and Consumer Configuration
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all
      properties:
        reconnect.backoff.ms: 5000
        reconnect.backoff.max.ms: 30000
    consumer:
      group-id: payment-service
      auto-offset-reset: earliest
      enable-auto-commit: false
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
        partition.assignment.strategy: org.apache.kafka.clients.consumer.CooperativeStickyAssignor
        reconnect.backoff.ms: 5000
        reconnect.backoff.max.ms: 30000
    #listener configuration
    listener:
      ack-mode: record

# Spring Security
security:
  admin:
    name: admin
    password: Admin@1234

  customer:
    name: customer
    password: Customer@1234

  # Authentication
  jwt:
    secret-key: 88cd2108b5347d973cf39cdf9053d7dd42704876d8c9a9bd8e2d168259d3ddf7
    expiration-time: 3600000

# Database
db:
  host: ${DB_HOST:localhost}
  port: ${DB_PORT:3307}
  name: ${DB_NAME:taskdb}